### ISSUE TITLE
missing parameter on conda update

### ISSUE THREAD

**Issue by scottrfrancis** [rpcme/aws-mchp-cryptoauth-workshop#8]
was previously noted in chime room

in lab1_macos.md,
step #12 after the trust platform install, command should read:

```
bin/conda update --offline ~/WorkDocs/microchip/TKO\ Lab/trustplatform-designsuite-1.2.3-0.tar.bz2 -p .
```

**Comment by rpcme** [comment]
Could this be a mac specific thing?  the -p flag is not required on windows.  I am ok with the change, just need to validate there's no unintended consequences on windows.

**Comment by scottrfrancis** [comment]
Could be...  I didn’t check windows. But did have to add this for Mac

**Comment by rpcme** [comment]
weird I think the instructions say to download to the ~/Downloads directory.  do you think this cause it?

@mangelino can you cross check this for Mac please?

**Comment by massi-ang** [comment]
There is an error in the Mac instructions: should be /Downloads/trust... instead of ~/Downloads/rust...   
fixing it

**Comment by scottrfrancis** [comment]
Nice catch… yes. I *did* move the download.  Moved it back to downloads and the command executes properly.

 

There *is* a typo in the command tho… ‘rust_platform’….

**Comment by rpcme** [comment]
@scottrfrancis can we close this issue then?

**Comment by scottrfrancis** [comment]
I concur

Scott FRANCIS
Partner Solutions Architect, IoT
e:  scofranc@amazon.com<mailto:scofranc@amazon.com> | m: +1 925 997 2922



[AWS Certified Solutions Architect - Associate]<https://www.certmetrics.com/amazon/public/badge.aspx?t=c&d=2018-12-27&i=1&ci=AWS00714974>


    [signature_1759461184] <https://aws.amazon.com/>
