### ISSUE TITLE
mac serial options/commands

### ISSUE THREAD

**Issue by scottrfrancis** [rpcme/aws-mchp-cryptoauth-workshop#9]
0. find device name
```
ls /dev/tty.usb*
```
example output:
```
/dev/tty.usbmodem14324102
```
substitute your device name in commands below or use `/dev/tty.usb` and tab for name completion.

1. screen (built in.. no additional install needed)
```
screen /dev/tty.usbmodem1411102 115200
```
use ctrl-a  then k to kill the session

2. minicom
```
minicom -b 115200 -D /dev/tty.usbmodem14324102
```
Enter, ctrl-a q to quit

3. picocom
```
picocom -b 115200 /dev/tty.usbmodem14324102
```
ctrl-a q to to quit

### to install minicom or picocom
```
brew install minicom
brew install picocom
```

4. Serial.app 
Free trial.  install from: https://www.decisivetactics.com/products/serial/

5. Chrome Serial Monitor app
Free. install from: https://chrome.google.com/webstore/detail/serial-monitor/ohncdkkhephpakbbecnkclhjkmbjnmlo?hl=en

6. Use Arduino built in monitor

**Comment by rpcme** [comment]
Good! I think the intent was to add only screen.  If you look at Lab 3, I had already communicated `ctrl-[`.

**Comment by scottrfrancis** [comment]
Seems like o have to repeat these all the time so I thought I would add em all ...
